'use client';

import { motion } from 'framer-motion';
import { Activity, Zap } from 'lucide-react';
import SignalsTable from './SignalsTable';

/**
 * SignalsSection - Wrapper section for live signals feed
 *
 * Features:
 * - Animated section header
 * - Live indicator badge
 * - Grid background with gradient overlay
 * - Full-width container for table
 */

export default function SignalsSection() {
  return (
    <section
      className="relative w-full bg-bg py-20 overflow-hidden"
      id="signals-feed"
      aria-label="Live trading signals"
    >
      {/* Background grid pattern */}
      <div
        className="absolute inset-0 bg-grid opacity-20 pointer-events-none"
        aria-hidden="true"
      />

      {/* Gradient overlay */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background:
            'radial-gradient(ellipse 100% 60% at 50% 40%, transparent 0%, rgba(11, 11, 15, 0.8) 100%)',
        }}
        aria-hidden="true"
      />

      {/* Accent glow spots */}
      <div
        className="absolute inset-0 overflow-hidden pointer-events-none"
        aria-hidden="true"
      >
        <div className="absolute -top-40 -left-40 w-80 h-80 bg-accentA/10 rounded-full blur-3xl" />
        <div className="absolute -bottom-40 -right-40 w-80 h-80 bg-accentB/10 rounded-full blur-3xl" />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-6">
        {/* Section Header */}
        <motion.div
          className="text-center mb-12"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          {/* Live Badge */}
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-success/10 border border-success/30 rounded-full mb-4">
            <div className="relative">
              <Zap className="w-4 h-4 text-success" />
              <div className="absolute inset-0 blur-sm bg-success opacity-50 animate-pulse" />
            </div>
            <span className="text-sm font-semibold text-success">
              Live Signal Feed
            </span>
            <div className="w-2 h-2 rounded-full bg-success animate-pulse" />
          </div>

          <h2 className="text-3xl md:text-4xl lg:text-5xl font-display font-bold text-text mb-4">
            Recent Trading Signals
          </h2>
          <p className="text-lg text-dim max-w-2xl mx-auto">
            Real-time AI-generated signals with entry/exit prices, stop-loss
            levels, and confidence scores
          </p>
        </motion.div>

        {/* Signals Table */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <SignalsTable />
        </motion.div>

        {/* Disclaimer */}
        <motion.p
          className="text-xs text-dim text-center mt-8 max-w-3xl mx-auto"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ delay: 0.4 }}
        >
          Signals are generated by AI models and provided for educational
          purposes only. Past performance does not guarantee future results.
          Always conduct your own research and never invest more than you can
          afford to lose.
        </motion.p>
      </div>
    </section>
  );
}
